# version: '3.8'

services:
  mongodb:
    image: mongo:8.0.8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: face_tracking_app

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env.backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    depends_on:
      - backend

volumes:
  mongo-data:
    driver: local