services:
  nginx:
    image: nginx:alpine
    container_name: backend_nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./backend/config/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/config/ssl:/etc/nginx/ssl:ro
    depends_on:
      auth_service:
        condition: service_healthy
      image_service:
        condition: service_started
      frontend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=512
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  image_service:
    build: 
      context: ./backend
      dockerfile: image_service/Dockerfile
    container_name: backend_image_service
    ports:
      - "8010:8010"
    env_file:
      - ./backend/.env.backend
    volumes:
      - ./backend/auth_service/resource_security/public/captures:/app/resource_security/public/captures
      - ./backend/auth_service/resource_security/public/enhance:/app/resource_security/public/enhance
      - ./backend/auth_service/resource_security/public/complete:/app/resource_security/public/complete
    environment:
      - PORT=8010
      - IMAGE_SERVICE_URL=http://backend_image_service:8010
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 6G
        reservations:
          cpus: '0.75'
          memory: 3G


  # video_service:
  #   build: 
  #     context: ./backend
  #     dockerfile: video_service/Dockerfile
  #   container_name: backend_video_service
  #   ports:
  #     - "8011:8011"
  #   environment:
  #     - PORT=8011
  #   networks:
  #     - app-network


  auth_service:
    build: 
      context: ./backend
      dockerfile: auth_service/Dockerfile
    container_name: backend_auth_service
    ports:
      - "8108:8108"
    volumes:
      - ./backend/auth_service/resource_security/public/captures:/app/resource_security/public/captures
      - ./backend/auth_service/resource_security/public/enhance:/app/resource_security/public/enhance
      - ./backend/auth_service/resource_security/public/complete:/app/resource_security/public/complete
      - ./backend/auth_service/resource_security/canvas:/app/resource_security/canvas
      - ./backend/auth_service/resource_security/consent_data.json:/app/resource_security/consent_data.json
    env_file:
      - ./backend/.env.backend
    environment:
      - IMAGE_SERVICE_URL=http://backend_image_service:8010
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 2G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: frontend_main
    ports:
      - "3010:3010"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    # environment:
      # - NEXT_PUBLIC_API_URL=https://192.168.1.107
      # - AUTH_SERVICE_URL=http://backend_auth_service:8108
      # - BACKEND_API_KEY=A1B2C3D4-E5F6-7890-GHIJ-KLMNOPQRSTUV
      # - NEXT_PUBLIC_API_KEY=A1B2C3D4-E5F6-7890-GHIJ-KLMNOPQRSTUV
    env_file:
      - ./frontend/.env.frontend
    depends_on:
      auth_service:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3010"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 3G
        reservations:
          cpus: '0.25'
          memory: 1G

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/config/mongod.conf:/etc/mongod.conf:ro
    environment:
      - MONGO_INITDB_DATABASE=eye_tracking

    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 1G

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongodb_data: